### ISSUE TITLE
for terminals without clipboard access, `Clipboard::new().unwrap()` crashes at startup

### ISSUE THREAD

**Issue by nzrq** [ndd7xv/heh#1]
https://github.com/ndd7xv/heh/blob/9970480f2cb0825e918c268bb8b02b80d5b5ab5c/src/app.rs#L64

This line is crashing at startup for my shell which does not support clipboard interaction.

A common way to avoid the crash is to use this pattern instead of `unwrap()`:

```rust
clipboard: Clipboard::new().unwrap_or_else(|e| {
    eprintln!("Failed to construct a Clipboard object: {}", e);
    std::process::exit(1)
}),
```

**Comment by ndd7xv** [comment]
Thanks for the issue!

I can try and address this soon so that a shell that doesn't support clipboard interaction simply won't be able to copy - I don't think the lack of a clipboard should stop the application from starting. I'll probably do this putting the clipboard in an `Option`.

**Comment by ndd7xv** [comment]
I just fixed this, but will still need to publish another release! Let me know if there's a specific time you'd want me to do that - if not, I might wait until next week until I've made more changes and added more features.

**Comment by nzrq** [comment]
No rush and thank you for the quick turnaround!
