### ISSUE TITLE
[BUG] `--version` missing

### ISSUE THREAD

**Issue by davidak** [ndd7xv/heh#80]
**Describe the bug**
The README sais `--version` exist, but it does not.

**To Reproduce**
```
[nix-shell:~/.cache/nixpkgs-review/pr-246402]$ heh --version
error: unexpected argument '--version' found

  tip: to pass '--version' as a value, use '-- --version'

Usage: heh [OPTIONS] <FILE>

For more information, try '--help'.
```

The **tip** is not helping here:

```
[nix-shell:~/.cache/nixpkgs-review/pr-246402]$ heh -- --version
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

**Expected behavior**
It is a basic option like `--help` that any CLI program should have.

**Desktop (please complete the following information):**
 - OS: NixOS 22.11.4588.93fddcf640c

**Additional context**
Noticed while reviewing the packaging for NixOS: https://github.com/NixOS/nixpkgs/pull/246402

**Comment by ndd7xv** [comment]
Thanks so much for the bug report :D I plan on fixing soon, didn't even know of https://github.com/NixOS/nixpkgs/pull/246402, but that's super cool :partying_face:
